# Mi for classification problems

In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("banana_quality_dataset.csv")
df.head()

,sample_id,variety,region,quality_score,quality_category,ripeness_index,ripeness_category,sugar_content_brix,firmness_kgf,length_cm,weight_g,harvest_date,tree_age_years,altitude_m,rainfall_mm,soil_nitrogen_ppm
0,1,Manzano,Colombia,1.88,Processing,2.11,Turning,16.83,3.53,21.44,146.92,2023-10-16,13.7,58.2,2440.5,183.6
1,2,Plantain,Guatemala,2.42,Processing,4.25,Ripe,16.73,4.09,26.11,160.48,2023-10-14,5.1,280.2,2374.6,109.8
2,3,Burro,Ecuador,3.57,Premium,6.24,Overripe,21.34,1.63,25.20,225.27,2023-09-08,17.7,1246.9,1191.5,147.7
3,4,Manzano,Ecuador,2.21,Processing,5.39,Ripe,16.75,3.31,13.08,137.80,2023-10-07,13.0,1150.2,2845.1,92.8
4,5,Red Dacca,Ecuador,2.35,Processing,5.84,Ripe,16.90,3.07,12.98,227.84,2023-10-02,4.8,526.0,2136.9,129.7

In [4]:
y=df['quality_category']

In [5]:
x=df.drop(columns=["quality_category","sample_id","harvest_date"],axis=1)

In [8]:
from sklearn.preprocessing  import OrdinalEncoder,MinMaxScaler
from sklearn.compose import ColumnTransformer
transformer=ColumnTransformer(transformers=[("t1",OrdinalEncoder(),[0,1,4]),
                                            ("t2",MinMaxScaler(),[2,3,5,6,7,8,9,10,11,12])])

X_transformed=transformer.fit_transform(x)

In [9]:
X_transformed=pd.DataFrame(X_transformed,columns=x.columns)

In [11]:
X_transformed.head()

,variety,region,quality_score,ripeness_index,ripeness_category,sugar_content_brix,firmness_kgf,length_cm,weight_g,tree_age_years,altitude_m,rainfall_mm,soil_nitrogen_ppm
0,5.0,1.0,3.0,0.323232,0.182274,0.262178,0.673333,0.573434,0.390133,0.650000,0.038585,0.723073,0.914165
1,6.0,4.0,2.0,0.505051,0.540134,0.247851,0.797778,0.807519,0.470445,0.172222,0.186782,0.689982,0.525540
2,1.0,3.0,1.0,0.892256,0.872910,0.908309,0.251111,0.761905,0.854181,0.872222,0.832109,0.095908,0.725118
3,5.0,3.0,2.0,0.434343,0.730769,0.250716,0.624444,0.154386,0.336117,0.611111,0.767557,0.926237,0.436019
4,7.0,3.0,2.0,0.481481,0.806020,0.272206,0.571111,0.149373,0.869403,0.155556,0.350868,0.570625,0.630332

In [12]:
#matual info classifer
from sklearn.feature_selection import mutual_info_classif
mutual_info=mutual_info_classif(X_transformed,y)
mutual_info=pd.Series(mutual_info)
mutual_info.index=X_transformed.columns
mutual_info.sort_values(ascending=False)

ripeness_index        0.913640
ripeness_category     0.232660
quality_score         0.220837
sugar_content_brix    0.159686
length_cm             0.065413
rainfall_mm           0.024998
firmness_kgf          0.008967
region                0.000000
variety               0.000000
weight_g              0.000000
tree_age_years        0.000000
altitude_m            0.000000
soil_nitrogen_ppm     0.000000
dtype: float64

In [14]:
from sklearn.feature_selection import chi2
import pandas as pd
#Apply chi-square test
chi_scores,_=chi2(X_transformed,y)

#create DataFrame with only chi-suARE scores 
chi_df=pd.DataFrame({
    'feature':X_transformed.columns,
    'chi2_score':chi_scores
})
#sort features ny importance 
chi_df=chi_df.sort_values(by='chi2_score',ascending=False)
print(chi_df)

               feature  chi2_score
4    ripeness_category   62.086388
3       ripeness_index   49.456131
5   sugar_content_brix   47.779138
7            length_cm   24.483735
2        quality_score   19.076129
1               region    1.768188
0              variety    0.864916
6         firmness_kgf    0.849285
8             weight_g    0.507458
9       tree_age_years    0.245139
10          altitude_m    0.227340
11         rainfall_mm    0.213058
12   soil_nitrogen_ppm    0.134461

In [15]:
from sklearn.feature_selection import chi2,SelectKBest
select_columns=SelectKBest(chi2,k=5)
best_features=select_columns.fit_transform(X_transformed,y)

In [17]:
selected_features=x.columns[select_columns.get_support()]
print(selected_features)

Index(['quality_score', 'ripeness_index', 'ripeness_category',
       'sugar_content_brix', 'length_cm'],
      dtype='object')

In [19]:
df=pd.read_csv("AQI.csv")
df.head()

,City,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
0,Ahmedabad,2015-01-01,NaN,NaN,0.92,18.22,17.15,NaN,0.92,27.64,133.36,0.00,0.02,0.00,NaN,NaN
1,Ahmedabad,2015-01-02,NaN,NaN,0.97,15.69,16.46,NaN,0.97,24.55,34.06,3.68,5.50,3.77,NaN,NaN
2,Ahmedabad,2015-01-03,NaN,NaN,17.40,19.30,29.70,NaN,17.40,29.07,30.70,6.80,16.40,2.25,NaN,NaN
3,Ahmedabad,2015-01-04,NaN,NaN,1.70,18.48,17.97,NaN,1.70,18.59,36.08,4.43,10.14,1.00,NaN,NaN
4,Ahmedabad,2015-01-05,NaN,NaN,22.10,21.42,37.76,NaN,22.10,39.33,39.31,7.01,18.89,2.78,NaN,NaN

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29531 entries, 0 to 29530
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   City        29531 non-null  object
 1   Date        29531 non-null  object
 2   PM2.5       24933 non-null  float64
 3   PM10        18391 non-null  float64
 4   NO          25949 non-null  float64
 5   NO2         25946 non-null  float64
 6   NOx         25346 non-null  float64
 7   NH3         19203 non-null  float64
 8   CO          27472 non-null  float64
 9   SO2         25677 non-null  float64
 10  O3          25509 non-null  float64
 11  Benzene     23908 non-null  float64
 12  Toluene     21490 non-null  float64
 13  Xylene      11422 non-null  float64
 14  AQI         24850 non-null  float64
 15  AQI_Bucket  24850 non-null  object
dtypes: float64(13), object(3)
memory usage: 3.6+ MB

In [21]:
df.drop('Date',axis=1,inplace=True)

In [22]:
df.shape

(29531, 15)

In [23]:
df.isnull().sum()

City              0
PM2.5          4598
PM10          11140
NO             3582
NO2            3585
NOx            4185
NH3           10328
CO             2059
SO2            3854
O3             4022
Benzene        5623
Toluene        8041
Xylene        18109
AQI            4681
AQI_Bucket     4681
dtype: int64

In [24]:
y=df['AQI_Bucket']
x=df.drop('AQI_Bucket',axis=1)

In [25]:
x.shape

(29531, 14)

In [29]:
from sklearn.preprocessing import OrdinalEncoder,MinMaxScaler
from sklearn.compose import ColumnTransformer
ct=ColumnTransformer(transformer=[("ob",OrdinalEmcoder(),[0]),
                    ("sc", MinMaxScaler(),[1,2,3,4,5,6,7,8,9,10,11,12,13]])
x_tranformed=ct.fit_transform(x)
x_transformed=pd.DataFrame(x_transfromed)

SyntaxError: closing parenthesis ']' does not match opening parenthesis '(' (3190660925.py, line 4)

In [31]:
from sklearn.feature_selection import mutual_info_classif
mf=mutual_info_classif(X_transformed,y)

ValueError: Unknown label type: unknown. Maybe you are trying to fit a classifier, which expects discrete classes on a regression target with continuous values.