# identify the bussiness problem

In [2]:
import pandas as pd 
import numpy as np

In [3]:
df=pd.read_csv("banana_quality_dataset.csv")

In [4]:
#basic checks
df.head()

,sample_id,variety,region,quality_score,quality_category,ripeness_index,ripeness_category,sugar_content_brix,firmness_kgf,length_cm,weight_g,harvest_date,tree_age_years,altitude_m,rainfall_mm,soil_nitrogen_ppm
0,1,Manzano,Colombia,1.88,Processing,2.11,Turning,16.83,3.53,21.44,146.92,2023-10-16,13.7,58.2,2440.5,183.6
1,2,Plantain,Guatemala,2.42,Processing,4.25,Ripe,16.73,4.09,26.11,160.48,2023-10-14,5.1,280.2,2374.6,109.8
2,3,Burro,Ecuador,3.57,Premium,6.24,Overripe,21.34,1.63,25.20,225.27,2023-09-08,17.7,1246.9,1191.5,147.7
3,4,Manzano,Ecuador,2.21,Processing,5.39,Ripe,16.75,3.31,13.08,137.80,2023-10-07,13.0,1150.2,2845.1,92.8
4,5,Red Dacca,Ecuador,2.35,Processing,5.84,Ripe,16.90,3.07,12.98,227.84,2023-10-02,4.8,526.0,2136.9,129.7

In [5]:
 df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   sample_id           1000 non-null   int64
 1   variety             1000 non-null   object
 2   region              1000 non-null   object
 3   quality_score       1000 non-null   float64
 4   quality_category    1000 non-null   object
 5   ripeness_index      1000 non-null   float64
 6   ripeness_category   1000 non-null   object
 7   sugar_content_brix  1000 non-null   float64
 8   firmness_kgf        1000 non-null   float64
 9   length_cm           1000 non-null   float64
 10  weight_g            1000 non-null   float64
 11  harvest_date        1000 non-null   object
 12  tree_age_years      1000 non-null   float64
 13  altitude_m          1000 non-null   float64
 14  rainfall_mm         1000 non-null   float64
 15  soil_nitrogen_ppm   1000 non-null   float64
dtypes: float64(10), int64(1), object(5)
memory usage: 125.1+ KB

In [6]:
df.shape

(1000, 16)

In [7]:
df.describe()

,sample_id,quality_score,ripeness_index,sugar_content_brix,firmness_kgf,length_cm,weight_g,tree_age_years,altitude_m,rainfall_mm,soil_nitrogen_ppm
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,500.500000,2.465160,4.042170,18.516830,2.706840,19.882100,164.738930,10.879600,723.556700,1972.992800,104.391300
std,288.819436,0.540909,1.753211,2.034812,1.289252,5.736318,49.163073,5.215554,427.372855,564.467912,53.607794
min,1.000000,0.920000,1.020000,15.000000,0.500000,10.000000,81.050000,2.000000,0.400000,1000.500000,10.000000
25%,250.750000,2.090000,2.447500,16.827500,1.590000,14.902500,122.397500,6.300000,353.950000,1498.750000,60.150000
50%,500.500000,2.440000,4.110000,18.500000,2.680000,19.890000,163.365000,10.700000,726.000000,1957.400000,104.100000
75%,750.250000,2.850000,5.562500,20.312500,3.820000,24.800000,205.775000,15.600000,1071.725000,2431.800000,149.850000
max,1000.000000,3.890000,7.000000,21.980000,5.000000,29.950000,249.890000,20.000000,1498.400000,2992.000000,199.900000

In [8]:
#drop 
df.drop(["sample_id","harvest_date"],axis=1,inplace=True)

In [9]:
df.shape

(1000, 14)

In [10]:
#EDA 
#preprocessing

In [11]:
 #target variable quality category
y=df['quality_category']

In [12]:
x =df.drop(['quality_category'],axis=1)

In [13]:
x.shape

(1000, 13)

In [14]:
#apply columntransformer 
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OrdinalEncoder,StandardScaler
ct=ColumnTransformer(transformers=[("oe",OrdinalEncoder(),[0,1,4]),
                                   ("sc",StandardScaler(),[2,3,5,6,7,8,9,10,11,12])])

In [15]:
x_transformed=ct.fit_transform(x)

In [16]:
x_transformed

array([[ 5.        ,  1.        ,  3.        , ..., -1.55763199,
         0.82864078,  1.47829873],
       [ 6.        ,  4.        ,  2.        , ..., -1.03791932,
         0.71183524,  0.1009444 ],
       [ 1.        ,  3.        ,  1.        , ...,  1.2251718 ,
        -1.38516968,  0.8082849 ],
       ...,
       [ 6.        ,  3.        ,  0.        , ..., -0.09494518,
         1.7412837 ,  1.59587776],
       [ 3.        ,  4.        ,  0.        , ...,  1.49626516,
        -1.34209875, -0.35257471],
       [ 7.        ,  3.        ,  3.        , ..., -1.32703876,
         1.57910303, -0.99086087]])

In [17]:
x_transformed=pd.DataFrame(x_transformed,columns=x.columns)
x_transformed

,variety,region,quality_score,ripeness_index,ripeness_category,sugar_content_brix,firmness_kgf,length_cm,weight_g,tree_age_years,altitude_m,rainfall_mm,soil_nitrogen_ppm
0,5.0,1.0,3.0,-1.082350,-1.102626,-0.829400,0.638798,0.271721,-0.362627,0.541038,-1.557632,0.828641,1.478299
1,6.0,4.0,2.0,-0.083531,0.118602,-0.878570,1.073376,1.086240,-0.086672,-1.108701,-1.037919,0.711835,0.100944
2,1.0,3.0,1.0,2.043584,1.254230,1.388129,-0.835662,0.927522,1.231846,1.308358,1.225172,-1.385170,0.808285
3,5.0,3.0,2.0,-0.471961,0.769163,-0.868736,0.468071,-1.186389,-0.548225,0.406757,0.998792,1.545781,-0.216332
4,7.0,3.0,2.0,-0.213007,1.025963,-0.794982,0.281824,-1.203830,1.284148,-1.166250,-0.462490,0.290520,0.472345
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,1.0,3.0,2.0,1.914108,0.512362,1.250456,-0.168275,1.407163,0.643306,0.291659,-0.734754,0.100866,1.280467
996,2.0,7.0,1.0,-0.157518,1.539564,-1.188335,-0.548530,-1.306735,0.016506,0.598587,-0.958090,-1.138442,1.420442
997,6.0,3.0,0.0,-1.452283,-1.502094,-0.662225,-0.331241,-0.579424,0.922720,1.442639,-0.094945,1.741284,1.595878
998,3.0,4.0,0.0,-0.823397,-1.542040,-0.731062,0.134378,1.121123,-0.045564,-0.514028,1.496265,-1.342099,-0.352575
999,7.0,3.0,3.0,0.415879,-0.771639,1.270123,-1.146075,0.360673,-1.207789,0.445123,-1.327039,1.579103,-0.990861

In [18]:
#feature selection
from sklearn.feature_selection import mutual_info_classif
mf=mutual_info_classif(x_transformed,y)

In [19]:
mf=pd.Series(mf)
mf.index=x_transformed.columns
mf.sort_values(ascending=False)

ripeness_index        0.913640
ripeness_category     0.230242
quality_score         0.192806
sugar_content_brix    0.155334
length_cm             0.065478
rainfall_mm           0.025749
variety               0.022100
region                0.012421
firmness_kgf          0.003276
weight_g              0.000000
tree_age_years        0.000000
altitude_m            0.000000
soil_nitrogen_ppm     0.000000
dtype: float64

In [20]:
x.drop(["firmness_kgf","variety","weight_g","altitude_m","soil_nitrogen_ppm"],axis=1,inplace=True)

In [21]:
x.shape

(1000, 8)

In [22]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   region              1000 non-null   object
 1   quality_score       1000 non-null   float64
 2   ripeness_index      1000 non-null   float64
 3   ripeness_category   1000 non-null   object
 4   sugar_content_brix  1000 non-null   float64
 5   length_cm           1000 non-null   float64
 6   tree_age_years      1000 non-null   float64
 7   rainfall_mm         1000 non-null   float64
dtypes: float64(6), object(2)
memory usage: 62.6+ KB

In [23]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [24]:
ct=ct=ColumnTransformer(transformers=[("oe",OrdinalEncoder(),[0,3,]),
                                   ("sc",StandardScaler(),[1,2,4,5,6,7])])

In [25]:
x_train_transform=ct.fit_transform(x_train)
x_train_transform=pd.DataFrame(x_train_transform)

In [26]:
x_test_transform=ct.transform(x_test)
x_test_transform=pd.DataFrame(x_test_transform)

In [27]:
#model bulding
from sklearn.neighbors import KNeighborsClassifier
kn=KNeighborsClassifier(n_neighbors=7,metric="minkowski",p=1)

In [28]:
#training
kn.fit(x_train_transform,y_train)

KNeighborsClassifier(n_neighbors=7, p=1)

In [29]:
#test
y_pred=kn.predict(x_test_transform)

In [30]:
#evolution
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score
ac=accuracy_score(y_test,y_pred)
ac

0.905

In [31]:
pr=precision_score(y_test,y_pred,average="micro")
pr

0.905

In [32]:
f1=f1_score(y_test,y_pred,average="micro")
f1

0.905

In [33]:
from sklearn.metrics import confusion_matrix,classification_report
cm=confusion_matrix(y_test,y_pred)
cm

array([[85,  0, 10,  0],
       [ 2,  3,  0,  0],
       [ 2,  0, 91,  0],
       [ 0,  0,  5,  2]])

In [34]:
df.quality_category.value_counts()

quality_category
Processing    506
Good          434
Unripe         35
Premium        25
Name: count, dtype: int64

In [35]:
cr=classification_report(y_test,y_pred)
print(cr)

              precision    recall  f1-score   support

        Good       0.96      0.89      0.92        95
     Premium       1.00      0.60      0.75         5
  Processing       0.86      0.98      0.91        93
      Unripe       1.00      0.29      0.44         7

    accuracy                           0.91       200
   macro avg       0.95      0.69      0.76       200
weighted avg       0.91      0.91      0.90       200

In [36]:
from sklearn.tree import DecisionTreeClassifier,plot_tree

In [37]:
model=DecisionTreeClassifier(criterion='gini',max_depth=2)
model.fit(x_train_transform,y_train)

DecisionTreeClassifier(max_depth=2)

In [39]:
#test
y_pred=model.predict(x_test_transform)

In [40]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score
ac=accuracy_score(y_test,y_pred)
ac

0.99