In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
# load dataset
df=pd.read_csv("loan_approved.csv")
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status (Approved)
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Loan_ID                 614 non-null    object
 1   Gender                  601 non-null    object
 2   Married                 611 non-null    object
 3   Dependents              599 non-null    object
 4   Education               614 non-null    object
 5   Self_Employed           582 non-null    object
 6   ApplicantIncome         614 non-null    int64
 7   CoapplicantIncome       614 non-null    float64
 8   LoanAmount              592 non-null    float64
 9   Loan_Amount_Term        600 non-null    float64
 10  Credit_History          564 non-null    float64
 11  Property_Area           614 non-null    object
 12  Loan_Status (Approved)  614 non-null    object
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB

In [4]:
df.tail()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status (Approved)
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [5]:
df.isnull().sum()

Loan_ID                    0
Gender                    13
Married                    3
Dependents                15
Education                  0
Self_Employed             32
ApplicantIncome            0
CoapplicantIncome          0
LoanAmount                22
Loan_Amount_Term          14
Credit_History            50
Property_Area              0
Loan_Status (Approved)     0
dtype: int64

In [6]:
num_cols = df.select_dtypes(include='number').columns
cat_cols = df.select_dtypes(include='object').columns

print("Numerical columns:", num_cols)
print("Categorical columns:", cat_cols)

Numerical columns: Index(['ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History'],
      dtype='object')
Categorical columns: Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'Property_Area', 'Loan_Status (Approved)'],
      dtype='object')

In [7]:
for col in num_cols:
    df[col].fillna(df[col].mean(), inplace=True)

In [8]:
for col in cat_cols:
    df[col].fillna(df[col].mode()[0], inplace=True)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Loan_ID                 614 non-null    object
 1   Gender                  614 non-null    object
 2   Married                 614 non-null    object
 3   Dependents              614 non-null    object
 4   Education               614 non-null    object
 5   Self_Employed           614 non-null    object
 6   ApplicantIncome         614 non-null    int64
 7   CoapplicantIncome       614 non-null    float64
 8   LoanAmount              614 non-null    float64
 9   Loan_Amount_Term        614 non-null    float64
 10  Credit_History          614 non-null    float64
 11  Property_Area           614 non-null    object
 12  Loan_Status (Approved)  614 non-null    object
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB

In [10]:
y=df["Loan_Status (Approved)"]

In [11]:
## input varibles 13 columns
x=df.drop(["Loan_Status (Approved)"],axis=1)

In [12]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    object
 1   Gender             614 non-null    object
 2   Married            614 non-null    object
 3   Dependents         614 non-null    object
 4   Education          614 non-null    object
 5   Self_Employed      614 non-null    object
 6   ApplicantIncome    614 non-null    int64
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         614 non-null    float64
 9   Loan_Amount_Term   614 non-null    float64
 10  Credit_History     614 non-null    float64
 11  Property_Area      614 non-null    object
dtypes: float64(4), int64(1), object(7)
memory usage: 57.7+ KB

In [13]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OrdinalEncoder,StandardScaler
ct=ColumnTransformer(transformers=[("oe",OrdinalEncoder(),[0,1,2,3,4,5,11]),
                                   ("sc",StandardScaler(),[6,7,8,9,10])])

In [14]:
x_transformed=ct.fit_transform(x)

In [15]:
x_transformed

array([[ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00, ...,
         0.00000000e+00,  2.79850543e-01,  4.51640451e-01],
       [ 1.00000000e+00,  1.00000000e+00,  1.00000000e+00, ...,
        -2.19273315e-01,  2.79850543e-01,  4.51640451e-01],
       [ 2.00000000e+00,  1.00000000e+00,  1.00000000e+00, ...,
        -9.57640999e-01,  2.79850543e-01,  4.51640451e-01],
       ...,
       [ 6.11000000e+02,  1.00000000e+00,  1.00000000e+00, ...,
         1.26937121e+00,  2.79850543e-01,  4.51640451e-01],
       [ 6.12000000e+02,  1.00000000e+00,  1.00000000e+00, ...,
         4.83366900e-01,  2.79850543e-01,  4.51640451e-01],
       [ 6.13000000e+02,  0.00000000e+00,  0.00000000e+00, ...,
        -1.59727534e-01,  2.79850543e-01, -2.41044061e+00]])

In [16]:
x_transformed=pd.DataFrame(x_transformed,columns=x.columns)
x_transformed

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,0.0,1.0,0.0,0.0,0.0,0.0,2.0,0.072991,-0.554487,0.000000,0.279851,0.451640
1,1.0,1.0,1.0,1.0,0.0,0.0,0.0,-0.134412,-0.038732,-0.219273,0.279851,0.451640
2,2.0,1.0,1.0,0.0,0.0,1.0,2.0,-0.393747,-0.554487,-0.957641,0.279851,0.451640
3,3.0,1.0,1.0,0.0,1.0,0.0,2.0,-0.462062,0.251980,-0.314547,0.279851,0.451640
4,4.0,1.0,0.0,0.0,0.0,0.0,2.0,0.097728,-0.554487,-0.064454,0.279851,0.451640
...,...,...,...,...,...,...,...,...,...,...,...,...
609,609.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.410130,-0.554487,-0.898095,0.279851,0.451640
610,610.0,1.0,1.0,3.0,0.0,0.0,0.0,-0.212557,-0.554487,-1.267279,-2.518655,0.451640
611,611.0,1.0,1.0,1.0,0.0,0.0,2.0,0.437174,-0.472404,1.269371,0.279851,0.451640
612,612.0,1.0,1.0,2.0,0.0,0.0,2.0,0.357064,-0.554487,0.483367,0.279851,0.451640
613,613.0,0.0,0.0,0.0,0.0,1.0,1.0,-0.134412,-0.554487,-0.159728,0.279851,-2.410441

In [17]:
from sklearn.feature_selection import mutual_info_classif
mf=mutual_info_classif(x_transformed,y)
mf=pd.Series(mf)
mf.index=x_transformed.columns
mf.sort_values(ascending=False)

Property_Area        0.161115
LoanAmount           0.015717
Dependents           0.014271
ApplicantIncome      0.011866
CoapplicantIncome    0.008685
Self_Employed        0.006270
Married              0.002005
Gender               0.001087
Loan_ID              0.000580
Education            0.000000
Loan_Amount_Term     0.000000
Credit_History       0.000000
dtype: float64

In [18]:
x.drop(["Loan_Amount_Term","Self_Employed","Dependents","Married","Loan_ID","CoapplicantIncome"], axis=1,inplace=True)

In [19]:
x.shape

(614, 6)

In [20]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [21]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Gender           614 non-null    object
 1   Education        614 non-null    object
 2   ApplicantIncome  614 non-null    int64
 3   LoanAmount       614 non-null    float64
 4   Credit_History   614 non-null    float64
 5   Property_Area    614 non-null    object
dtypes: float64(2), int64(1), object(3)
memory usage: 28.9+ KB

In [22]:
ct=ColumnTransformer(transformers=[("oe",OrdinalEncoder(),[0,1,5]),
                                   ( "sc",StandardScaler(),[2,3,4])])

In [23]:
x_train_transform=ct.fit_transform(x_train)
x_train_transform=pd.DataFrame(x_train_transform)
x_train_transform

       0    1    2         3         4         5
0    1.0  1.0  0.0  0.029453 -0.217414  0.464852
1    0.0  1.0  1.0 -0.170703 -0.335926  0.464852
2    1.0  0.0  0.0  0.500399 -0.217414  0.464852
3    0.0  0.0  0.0 -0.262821 -0.430735  0.464852
4    0.0  0.0  2.0 -0.450148  0.138120  0.464852
..   ...  ...  ...       ...       ...       ...
486  1.0  0.0  2.0  0.068402  1.975048  0.464852
487  1.0  1.0  1.0 -0.531911 -0.644055  0.464852
488  1.0  0.0  2.0  0.137182  0.375143 -2.354931
489  1.0  0.0  1.0 -0.208107 -0.596651 -2.354931
490  1.0  0.0  1.0 -0.116607  0.114418  0.464852

[491 rows x 6 columns]

In [24]:
x_test_transform=ct.fit_transform(x_test)
x_test_transform=pd.DataFrame(x_test_transform)

In [25]:
from imblearn.over_sampling import SMOTE

smote=SMOTE()
x_smote,y_smote=smote.fit_resample(x_train_transform,y_train)

In [26]:
from collections import Counter
print(Counter(y_train))
print(Counter(y_smote))

Counter({'Y': 340, 'N': 151})
Counter({'Y': 340, 'N': 340})

In [27]:
from sklearn.svm import SVC 
svclassifier=SVC()
svclassifier.fit(x_smote,y_smote)

SVC()

In [28]:
y_pred=svclassifier.predict(x_test_transform)

In [29]:
from sklearn.metrics import accuracy_score,recall_score,precision_score,classification_report,f1_score
acc=accuracy_score(y_test,y_pred)

In [30]:
acc

0.7479674796747967

In [31]:
from sklearn.metrics import f1_score

f1 = f1_score(y_test, y_pred, pos_label='Y')

print(f1)

0.8359788359788359

In [32]:
from sklearn.model_selection import GridSearchCV
param_grid={'C':[0.5,5,10,50,60,70],
            'gamma':[1,0.1,0.01,0.001,0.0001],
            'random_state':(list(range(1,20)))}

model=SVC()
grid=GridSearchCV(model,param_grid,refit=True,verbose=1,scoring='f1',cv=5)

grid.fit(x_smote,y_smote)

Fitting 5 folds for each of 570 candidates, totalling 2850 fits

GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': [0.5, 5, 10, 50, 60, 70],
                         'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
                         'random_state': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
                                          13, 14, 15, 16, 17, 18, 19]},
             scoring='f1', verbose=1)

In [33]:
print(grid.best_params_)

{'C': 0.5, 'gamma': 1, 'random_state': 1}

In [34]:
from sklearn.svm import SVC 
svclassifier=SVC(C=0.5,gamma=1,random_state=1)
svclassifier.fit(x_smote,y_smote)

SVC(C=0.5, gamma=1, random_state=1)

In [35]:
y_pred=svclassifier.predict(x_test_transform)

In [36]:
from sklearn.metrics import accuracy_score,recall_score,precision_score,classification_report,f1_score
acc=accuracy_score(y_test,y_pred)
acc

0.6991869918699187

In [37]:
from sklearn.metrics import f1_score

f1 = f1_score(y_test, y_pred, pos_label='Y')

print(f1)

0.7885714285714286

In [38]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

In [39]:
mod1=LogisticRegression(random_state=42)
mod2=DecisionTreeClassifier(random_state=42)
mod3=SVC(probability=True,random_state=42)

In [40]:
voting_clf=VotingClassifier(estimators=[
    ('lr',mod1),
    ('dt',mod2),
    ('svc',mod3)
],voting='soft')

In [42]:
voting_clf.fit(x_smote,y_smote)

#predict
y_pred=voting_clf.predict(x_test_transform)
acc=accuracy_score(y_test,y_pred)

acc

0.6097560975609756